spring:
  datasource:
    #url: jdbc:h2://localhost:8082/review;
    url: jdbc:h2:tcp://localhost/~/review;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none  #새로 생성 : create, 새로 생성되지 않음 : none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9099
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: review
          destination: ecomarket
          contentType: application/json
        event-out:
          destination: ecomarket
          contentType: application/json

#logging:
#  level:
#    org.hibernate.SQL: debug #로거를 이용해서 sql이 출력됨
