apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypage
  namespace: ecomarket
  labels:
    app: mypage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypage
  template:
    metadata:
      labels:
        app: mypage
    spec:
      containers:
        - name: mypage
          image: 104844728320.dkr.ecr.ap-northeast-2.amazonaws.com/mypage:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080