apiVersion: v1
kind: Service
metadata:
  name: mypage-svc
  namespace: ecomarket
  labels:
    app: mypage
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: mypage
  type: NodePort